config/routes.rb
Rails.application.routes.draw do
  get 'learning/index'

  root to: 'static_pages#home'
  
  get "static_pages/seminar" => 'static_pages#seminar'
  get "static_pages/seminar2" => 'static_pages#seminar2'
  get "static_pages/middle" => 'static_pages#middle'
  get "static_pages/pmo" => 'static_pages#pmo'
  get "static_pages/about" => 'static_pages#about'
  get "static_pages/approach" => 'static_pages#approach'
  get "static_pages/member" => 'static_pages#member'  
  get "static_pages/voice" => 'static_pages#voice'  
  get "static_pages/privacy" => 'static_pages#privacy' 
  get "static_pages/development" => 'static_pages#development' 
  get "static_pages/media" => 'static_pages#media'
  get "static_pages/sitemap" => 'static_pages#sitemap' 
  get "static_pages/strength" => 'static_pages#strength'  
  get "static_pages/consulting" => 'static_pages#consulting' 
  get "static_pages/consulting2" => 'static_pages#consulting2'
  get "static_pages/bot" => 'static_pages#bot' 
  get "static_pages/service" => 'static_pages#service'
  
  
  ##### メディアリンク
  get "static_pages/ainow" => redirect("http://ainow.ai/")
  get "static_pages/robotstart" => redirect("https://robotstart.info/")
  get "static_pages/ai4u" => redirect("http://ai-4-u.com/")
  get "static_pages/seamless" => redirect("http://shiropen.com/")
  get "static_pages/mit" => redirect("https://www.technologyreview.jp/")
  get "static_pages/deeplearning" => redirect("https://github.com/dennybritz/deeplearning-papernotes/blob/master/README.md")
  
  get "static_pages/iotnews" => redirect("https://iotnews.jp/")
  get "static_pages/iottoday" => redirect("http://iottoday.jp/")
  get "static_pages/monoist" => redirect("http://monoist.atmarkit.co.jp/")
  get "static_pages/techfactory" => redirect("http://techfactory.itmedia.co.jp/")
  
  get "static_pages/bcbiz" => redirect("http://gaiax-blockchain.com/")
  get "static_pages/btcn" => redirect("https://btcnews.jp/")
  get "static_pages/doublehash" => redirect("http://doublehash.me/")
  
  get "static_pages/netcommerce" => redirect("https://www.netcommerce.co.jp/blog")
  get "static_pages/itpro" => redirect("http://itpro.nikkeibp.co.jp/")
  get "static_pages/itmedia" => redirect("http://www.itmedia.co.jp/")
  get "static_pages/techcrunch" => redirect("http://jp.techcrunch.com/")
  get "static_pages/bridge" => redirect("http://thebridge.jp/")
  get "static_pages/cloud" => redirect("https://cloud.watch.impress.co.jp/")
  
  get "static_pages/moguravr" => redirect("http://www.moguravr.com/")
  get "static_pages/vrbeat" => redirect("http://www.vrbeat.net/")
  
  get "static_pages/drone" => redirect("https://www.drone.jp/")
  get "static_pages/dronemedia" => redirect("http://dronemedia.jp/")
  get "static_pages/bank" => redirect("https://dronebank.jp/")
  
  get "static_pages/makers" => redirect("http://makerslove.com/")
  get "static_pages/itmedia3d" => redirect("http://www.itmedia.co.jp/keywords/3d_printer.html")
  
  get "static_pages/marketing" => redirect("http://marketing.itmedia.co.jp/")
  get "static_pages/digiday" => redirect("http://digiday.jp/")
  get "static_pages/markezine" => redirect("https://markezine.jp/")
  
  get "static_pages/fintechonline" => redirect("https://fintechonline.jp/")
  get "static_pages/itmediafintech" => redirect("http://www.itmedia.co.jp/enterprise/subtop/fintech/index.html")
  get "static_pages/finte" => redirect("https://www.enigma.co.jp/media/")
 
  ##### パートナーリンク
  get "static_pages/kikagaku" => redirect("https://www.kikagaku.co.jp/")
  get "static_pages/justincase" => redirect("https://justincase.jp/")
  get "static_pages/glc" => redirect("https://geeklabs.co.jp/")
  get "static_pages/aisprits" => redirect("http://aispirits.com/") 
 
  ##### ノウハウ伝授リンク
  get "learning" => 'learning#index' 
  get "learning/shin-nihon" => redirect("http://www.meti.go.jp/committee/sankoushin/shin_sangyoukouzou/pdf/013_06_00.pdf")
  get "learning/business1" => 'learning#business1'
  get "learning/business2" => 'learning#business2'
  get "learning/business3" => 'learning#business3'
  
  get "learning/data1" => 'learning#data1'
  get "learning/data2" => 'learning#data2'
  
  get "static_pages/learning/business1" => redirect("http://www.edutech.co.jp/learning/business1")
  get "learning/seminar" => redirect("http://www.edutech.co.jp/static_pages/seminar")
  get "static_pages/dx-media" => redirect("https://www.dx-media.net/")


  ##### 問い合わせフォーム
  get 'inquiry' => 'inquiry#index' 
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  
  ##### 問い合わせ確認画面
  post 'inquiry/confirm' => 'inquiry#confirm'
  ##### 問い合わせ完了画面
  post 'inquiry/thanks' => 'inquiry#thanks'
  
  ##### 申し込みフォーム
  get 'reserve' => 'reserve#index' 
  get 'reserve/confirm' => redirect("/reserve")
  get 'reserve/thanks' => redirect("/reserve")
  ##### 申し込み確認画面
  post 'reserve/confirm' => 'reserve#confirm'
  ##### 申し込み完了画面
  post 'reserve/thanks' => 'reserve#thanks'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/views/static_pages/approach.html.erb
        <div class="jumbotron" style="background:url(<%= asset_path "main.png" %>) no-repeat; background-site:cover;">
            <h1>弊社のAIビジネス支援アプローチ</h1>
        </div>
        


<div class="exp">            
    <div class="row">
        <h4>アプローチ</h4>
        <div class="col-xs-12" style="background:#A8ACAB; height:1px;" ></div>
            
        <h1>テクノロジー×ビジネス</h1>
        <p>AIやブロックチェーンなどの最新テクノロジーをビジネスで活かすことが必須の時代に突入しました。
        しかしながら、テクノロジーを活かしてビジネスを考えられる経営企画担当者やコンサルタントはどのくらいいるのでしょうか？
        いわゆる一流のコンサルファームのコンサルタントですら、AIやブロックチェーンなどでビジネスを考えられる方は一握りでしかありません。
        一方でAIなどの開発ができるエンジニアはビジネス力が不足している方が多く見受けられます。
        弊社はテクノロジーとビジネス戦略双方のエキスパートにより、テクノロジーでビジネスを考えることが必須の時代に必要なスキル獲得を支援します。</p>
         
        <h1>コンサルティング×教育</h1>
        <p>高いお金を払ってレポートを受領するだけの従来のコンサルティングは本当に意味があるのでしょうか？
        結局はレポートだけで何も残らないといったことも少なくありません。
        弊社は研修を基礎としたコンサルティングサービスを提供することで、
        お客様社内の人員育成とビジネス支援を同時に提供します。これにより、
        新規事業立案などのコンサルティング成果はもとより、お客様の人材育成そのものも目的として長期的に効果のあるコンサルティングをご提供します。</p>
    　
 
        <h4>3つの思考ノウハウ</h4>
        <div class="col-md-12" style="background:#A8ACAB; height:1px;" ></div>


        <h1>論点思考</h1>
        <p>論点思考は戦略コンサルタントに必要な課題解決スキルです。ロジカルシンキングやフレームワーク思考では達成できない真の課題解決を発見するためのコンサルティング技法を活用します。
        </p>
        <h1>デザイン思考</h1>
        <p>デザイン思考はシリコンバレーを中心に広まったビジネス発想術です。観察や体験を通じて顧客のニーズやインサイトから「本当の課題」を見つけ出し、ビジネスを発想することを重視します。弊社はリーンスタートアップやデザイン思考の手法を活用してサービスを提供しており、テクノロジー×ビジネスと同時にデザイン思考などの手法も学ぶことができ、より実践的なビジネスノウハウを取得できます。
        </p>
        <h1>データ／テクノロジー思考</h1>
        <p>顧客起点だけでは顧客の範囲（ニーズ／インサイト）を超えるイノベーションは起きません。顧客がAIやブロックチェーンを知らない限り、それで解決できるニーズを見つけることができないからです。AI・IoT・ブロックチェーンなどのテクノロジーは何ができるのか？　どういったデータからどういったビジネスが創造できるのか？といったデータとテクノロジー起点の発想が顧客を超えたビジネスを創造することができます。２５１のトレーニングではデータやテクノロジー起点の発想を重視したサービスを提供しています。
        </p>
    
    </div>
</div>



        <div class="col-xs-12" style="background:white; height:100px;">     
            <div class="logo2">
                <%= link_to image_tag("inquiry2.png"),inquiry_path %>
            </div>
        </div>
</div>

app/views/static_pages/bot.html.erb
         <div class="jumbotron" style="background:url(<%= asset_path "main.png" %>) no-repeat; background-site:cover;">
            <h1>チャットボット導入<br>コンサルティング</h1>
            <p>UXを追求した効果的なチャット対話を世界最高精度のチャットボットで実現します。</p>
        </div>
        
<div class="container">   
<div class="exp">            
    <div class="row">

        <div class="col-md-8 col-md-offset-2" style="background:#ffffff; " >
            <h4>効果的なチャットボット導入のステップ</h4>
            <h1>■チャットボットの構築には次の5つのステップを必要とします。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot3.png" %>><br><br>
            <h1>■チャットボットは有人対応と自己対応のギャップを埋める新たなユーザーインターフェースであり、チャットボット特有の顧客体験を踏まえて導入業務範囲を特定します。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot5.png" %>><br><br>
            <h1>■対話設計においては想定ユーザをペルソナとして定義し、チャットボット対話のユーザーストーリーを洗い出すことで、UXデザインとして対話フローを設計します。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot6.png" %>><br><br>
            <h1>■その他に必要に応じてビジュアル・キャラクターデザインなどを実施。チャットボットにおけるUXをまとめると次の4つのUX対応が必要となります。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot7.png" %>><br><br>
            <h1>■こうしたUXデザインに失敗すると顧客に煙たがられて、クレームの発生源となってしまい、使われないチャットボットとなるリスクがあります。しかしながら、UXデザインを十分に実施しているベンダーは少ないのが現状です。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot1.png" %>><br><br>
            <h1>■加えて、チャットボットの機能面の差別化としては要素は次の6つの要素がどれだけ対応できているかを精査することになります。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot8.png" %>><br><br>
            <h1>■弊社は世界最高制度のIBM Watsonをチャットボット構築プロフェッショナルのGLC社協力により低コストで構築することが可能です。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot9.png" %>><br><br>
            <h1>■つまりチャットボットを効果的にする差別化要素は「チャットボット機能の精度」と「UXデザインの追求力」の2つがキーとなります。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot2.png" %>><br><br>
            <h1>■弊社はビジネスデザイナーにより高品質なチャットボット構築を低コストで実現いたします。</h1>
            <img class="img-responsive center-block" src=<%= asset_path "bot10.png" %>><br><br>
    　　</div>
        <div class="col-xs-12" style="background:white; height:100px;">     
            <div class="logo2">
                <%= link_to image_tag("inquiry2.png"),inquiry_path %>
            </div>
        </div>
        
     </div>
</div>

app/views/static_pages/home.html.1.erb
        <div class="jumbotron" style="background:url(<%= asset_path "main.png" %>) no-repeat; background-site:cover;">
            <h1>AI人材育成<br>×<br>コンサルティング</h1>
            <p>あなたはAI・IoT・ブロックチェーンのビジネス活用に困っていませんか？<br>
               エデュテックパートナーズはクライアントと二人三脚で、テクノロジービジネスに向けた自立自走を支援する唯一無二の育成支援型コンサルティングカンパニーです。
            </p>
        </div>
        
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2>AI人材育成<br>×<br>自立自走支援<br></h2>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="padding:0; background:white; height:300px;">
            <div class = "logo2">
                <%= link_to image_tag("service1.png"), static_pages_seminar_path %> 
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="padding:0; background:white; height:300px;">
            <div class = "logo2">
                <%= link_to image_tag("service2.png"), static_pages_middle_path %>
            </div>
        </div>
        <div class="ccol-md-4 col-sm-4 col-xs-12" style="padding:0; background:white; height:300px;">
            <div class = "logo2">
                <%= link_to image_tag("service3.png"), static_pages_pmo_path %>
            </div>
        </div>
        <div class="col-xs-12" style="padding:0; background:white; height:100px;">
            <div class="logo2">
                <%= link_to image_tag("yoyaku.png"), reserve_path %>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-xs-12" style="padding:0; background:#E0FFFF; height:150px;">
            <h2>AIスキルを学びたい！</h2>
            <h8><center>AIスキルを獲得するための初学者向けのコンテンツを一部無料提供しています。</h8></center>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12" style="background:#E0FFFF; height:300px;">
            <div class= "gaiyo">
                <a href="#">
                <div class="icon"><%= image_tag "thinking.png" %></div>
                <h1>AIビジネスモデル立案講座（基礎編）</h1>
                <p>
                AIの全体像と基礎知識を理解した上で、AIビジネスモデルを立案するための初歩的なスキルを身に着けます。
                </p>
                </a>
            </div>
        </div>
        
        <div class="col-md-6 col-sm-6 col-xs-12" style="background:#E0FFFF; height:300px;">
            <div class= "gaiyo">
                <a href="#">
                <div class="icon"><%= image_tag "teacher.png" %></div>
                <h1>デジタル戦略立案／デジタルビジネスモデル立案</h1>
                <p>AIビジネス企画立案およびデジタル戦略立案について、本物の戦略レポートから内容を学習します。
                </p>
                </a>
            </div>
        </div>
    </div>  

    
    
    <div class="row">
        <div class="col-xs-12" style="padding:0; background:#C0C4F6; height:150px;">
            <h2>コンサルティングノウハウ<br>×<br>独自アプローチ</h2>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#C0C4F6; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/strength">
                <div class="icon"><%= image_tag "develop.png" %></div>
                <h1>弊社の強み</h1>
                <p>
                戦略コンサルファームを超えるコンサルティング成果を低コストで提供
                </p>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#C0C4F6; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/member">
                <div class="icon"><%= image_tag "teacher.png" %></div>
                <h1>専門家集団</h1>
                <p>弊社サービスを提供するコンサルタントおよび研修講師陣の経歴及び実績
                </p>
                </a>
            </div>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#C0C4F6; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/approach">
                <div class="icon"><%= image_tag "approach.png" %></div>
                <h1>アプローチ</h1>
                <p>サービスに用いるノウハウやアプローチ方法のご説明
                </p>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12" style="padding:0; background:#F1F3FE; height:150px;">
            <h2>次世代ビジネスモデル構築<br>×<br>AI開発支援</h2>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#F1F3FE; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/consulting">
                <div class="icon"><%= image_tag "approach.png" %></div>
                <h1>次世代ビジネス支援</h1>
                <p>AI×IoT×ブロックチェーンによるデジタル戦略・ビジネスモデル構築支援
                </p>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#F1F3FE; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/bot">
                <div class="icon"><%= image_tag "teacher.png" %></div>
                <h1>チャットボット導入支援</h1>
                <p>UXデザイン×世界最高チャットボットによる高品質なチャットボット導入
                </p>
                </a>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" style="background:#F1F3FE; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/development">
                <div class="icon"><%= image_tag "develop.png" %></div>
                <h1>AIモデル構築支援</h1>
                <p>データサイエンティストによるAIモデル開発・データ分析までのトータル支援
                </p>
                </a>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-xs-12" style="padding:0; background:#ffffff; height:80px;">
            <h2>中国マーケティング支援<br>（準備中）</h2>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12" style="background:#ffffff;">
            <div class= "gaiyo">
            <a href="#">
                <img class="img-responsive center-block" src=<%= asset_path "china.png" %>>
            </a>
            <br><br>
            </div>
        </div>
    </div>
    

    <div class="row">
        <div class="col-xs-12" style="padding:0; background:#C0C4F6; height:150px;">
            <h2>最新テクノロジー情報<br>×<br>学習コンテンツ</h2>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12" style="background:#C0C4F6; height:300px;">
            <div class= "gaiyo">
                <a href="static_pages/media">
                <div class="icon"><%= image_tag "media.png" %></div>
                <h1>最新テクノロジー動向</h1>
                <p>最新のテクノロジー情報を取得できるメディアを
                テクノロジー分類ごとにピックアップし、最新記事を紹介します。
                </p>
                </a>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12" style="background:#C0C4F6; height:300px;">
            <div class= "gaiyo">
                <a href="learning">
                <div class="icon"><%= image_tag "learning1.png" %></div>
                <h1>ノウハウ伝授します！</h1>
                <p>テクノロジー担当講師柴田が提供するテクノロジー学習コンテンツ。自立自走学習支援のためのコンテンツを提供します。
                </p>
                </a>
            </div>
        </div>
        <div class="col-xs-12" style="padding:0; background:#C0C4F6; height:100px;">
            <div class="logo2">
                <%= link_to image_tag("yoyaku.png"), reserve_path %>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/sitemap.html.erb
        <div class="jumbotron" style="background:url(<%= asset_path "main.png" %>) no-repeat; background-site:cover;">
            <h1>サイトマップ</h1>
        </div>

<div class="exp">
<div class="container">
    <div class="row">
        <div class="col-md-4 col-xs-12" style="background:#ffffff" >

        <h1>弊社の説明ページ</h1>
        <h3>
         <%= link_to "会社概要", static_pages_about_path %><br> 
         <%= link_to "弊社サービスのアプローチ", static_pages_approach_path %><br> 
         <%= link_to "弊社の研修実施担当者", static_pages_member_path %><br> 
        </h3>
    　　</div>
    　　
   
        <div class="col-md-4 col-xs-12" style="background:#ffffff" >
        <h1>弊社サービスの説明ページ</h1>
         <h3>
         <%= link_to "AIビジネス研修サービス", static_pages_seminar_path %><br> 
         <%= link_to "弊社のAIコンサルティングなど各種サービスの説明", static_pages_service_path %><br>
         <%= link_to "中長期自立自走支援サービス", static_pages_pmo_path %><br> 
         <%= link_to "AI開発支援体制", static_pages_development_path %><br> 
        </h3>
        </div>
        
        
        <div class="col-md-4 col-xs-12" style="background:#ffffff" >
        <h1>学習支援向けページ</h1>
        <h3>
         <%= link_to "お薦めのテクノロジーメディア", static_pages_media_path %><br> 
         <%= link_to "AIビジネス推進人材に必要なスキルとその育成方法", learning_business1_path %><br> 
         <%= link_to "AI（人工知能）開発スキルの最適な学び方を学ぶ講座", learning_data1_path %><br>
         <%= link_to "超初心者のためのAI（人工知能／機械学習）によるビジネスモデル立案検討講座（基礎編）", learning_business2_path %><br> 
         <%= link_to "あなたの会社でデジタルトランスフォーメーション（DX）を実施する方法", learning_business3_path %><br> 
        </h3>
        <h1>弊社連絡ページ</h1>    
        <h3>
         <%= link_to "お問合せ", inquiry_path %><br>
         <%= link_to "セミナーの予約", reserve_path %><br> 
        </h3>
        </div>
   
    </div>
</div>
</div>

app/views/static_pages/voice.html.erb
        <div class="col-xs-12" style="background:white; height:100px;">     
            <div class="logo2">
                <%= link_to image_tag("voice.png"), static_pages_voice_path %>
            </div>
        </div>


<div class="exp">  
<div class="container"> 
    </div>
        <h4>受講生の声</h4>
        <div class="col-md-12" style="background:#A8ACAB; height:1px;" >
        </div><br>
        
    <div class = "row">
        <div class="col-xs-12" style="background:#ffffff;" >
            <h1>佐藤次郎</h1>
            <h1>株式会社エンペラー</h1>
            <p>
            初めの印象は「ビジネススクールというと仰々しい所なんだろう」「論理思考の講師はロジックばかり
            を振り回すような人」という勝手なイメージを持っていました。しかし、グロービスでは授業が始まる前に
            、初めて受講を開始する人向けにオリエンテーションを開催しています。
            私も緊張しながら参加したのですが、スクールの責任者として出てきた
            元気よく説明を始めた女性スタッフを見て、イメージがすぐに覆されました。
            オリエンテーションでは、一緒に学び始める方と話をする機会もあり、楽しく学べそうだと思いました。
            ただし、「楽しい」というのと「楽」なのは違います。クリティカル・シンキングの初回クラス
            で提出する課題を「これで充分だろう」というところまで考えてクラスに臨んだのですが、
            打ちのめされました（笑）。その時は「いつも考えているのとは違う視点が必要なんだな」
            と感じた瞬間でしたね。
            </p> 
        </div>
        <div class="col-xs-12" style="background:#ffffff;" >
            <h1>佐藤次郎</h1>
            <h1>株式会社エンペラー</h1>
            <p>
            初めの印象は「ビジネススクールというと仰々しい所なんだろう」「論理思考の講師はロジックばかり
            を振り回すような人」という勝手なイメージを持っていました。しかし、グロービスでは授業が始まる前に
            、初めて受講を開始する人向けにオリエンテーションを開催しています。
            私も緊張しながら参加したのですが、スクールの責任者として出てきた
            元気よく説明を始めた女性スタッフを見て、イメージがすぐに覆されました。
            オリエンテーションでは、一緒に学び始める方と話をする機会もあり、楽しく学べそうだと思いました。
            ただし、「楽しい」というのと「楽」なのは違います。クリティカル・シンキングの初回クラス
            で提出する課題を「これで充分だろう」というところまで考えてクラスに臨んだのですが、
            打ちのめされました（笑）。その時は「いつも考えているのとは違う視点が必要なんだな」
            と感じた瞬間でしたね。
            </p> 
        </div>

        <div class="col-xs-12" style="background:#ffffff;" >
            <h1>佐藤次郎</h1>
            <h1>株式会社エンペラー</h1>
            <p>
            初めの印象は「ビジネススクールというと仰々しい所なんだろう」「論理思考の講師はロジックばかり
            を振り回すような人」という勝手なイメージを持っていました。しかし、グロービスでは授業が始まる前に
            、初めて受講を開始する人向けにオリエンテーションを開催しています。
            私も緊張しながら参加したのですが、スクールの責任者として出てきた
            元気よく説明を始めた女性スタッフを見て、イメージがすぐに覆されました。
            オリエンテーションでは、一緒に学び始める方と話をする機会もあり、楽しく学べそうだと思いました。
            ただし、「楽しい」というのと「楽」なのは違います。クリティカル・シンキングの初回クラス
            で提出する課題を「これで充分だろう」というところまで考えてクラスに臨んだのですが、
            打ちのめされました（笑）。その時は「いつも考えているのとは違う視点が必要なんだな」
            と感じた瞬間でしたね。
            </p> 
        </div>
        <div class="col-xs-12" style="background:#ffffff;" > 
            <h1>佐藤次郎</h1>
            <h1>株式会社エンペラー</h1>
            <p>
            初めの印象は「ビジネススクールというと仰々しい所なんだろう」「論理思考の講師はロジックばかり
            を振り回すような人」という勝手なイメージを持っていました。しかし、グロービスでは授業が始まる前に
            、初めて受講を開始する人向けにオリエンテーションを開催しています。
            私も緊張しながら参加したのですが、スクールの責任者として出てきた
            元気よく説明を始めた女性スタッフを見て、イメージがすぐに覆されました。
            オリエンテーションでは、一緒に学び始める方と話をする機会もあり、楽しく学べそうだと思いました。
            ただし、「楽しい」というのと「楽」なのは違います。クリティカル・シンキングの初回クラス
            で提出する課題を「これで充分だろう」というところまで考えてクラスに臨んだのですが、
            打ちのめされました（笑）。その時は「いつも考えているのとは違う視点が必要なんだな」
            と感じた瞬間でしたね。
            </p> 
        </div>
    </div>
    
    </div>
        <div class="col-xs-12" style="background:white; height:100px;">     
            <div class="logo2">
                <%= link_to image_tag("yoyaku.png"), reserve_path %>
            </div>
        </div>
    </div>
</div>
</div>