config/routes.rb
Rails.application.routes.draw do
  get 'learning/index'

  root to: 'static_pages#home'
  
  get "static_pages/seminar" => 'static_pages#seminar'
  get "static_pages/seminar2" => 'static_pages#seminar2'
  get "static_pages/middle" => 'static_pages#middle'
  get "static_pages/pmo" => 'static_pages#pmo'
  get "static_pages/about" => 'static_pages#about'
  get "static_pages/approach" => 'static_pages#approach'
  get "static_pages/member" => 'static_pages#member'  
  get "static_pages/voice" => 'static_pages#voice'  
  get "static_pages/privacy" => 'static_pages#privacy' 
  get "static_pages/development" => 'static_pages#development' 
  get "static_pages/media" => 'static_pages#media'
  get "static_pages/sitemap" => 'static_pages#sitemap' 
  get "static_pages/strength" => 'static_pages#strength'  
  get "static_pages/consulting" => 'static_pages#consulting' 
  get "static_pages/consulting2" => 'static_pages#consulting2'
  get "static_pages/bot" => 'static_pages#bot' 
  get "static_pages/service" => 'static_pages#service'
  
  
  ##### メディアリンク
  get "static_pages/ainow" => redirect("http://ainow.ai/")
  get "static_pages/robotstart" => redirect("https://robotstart.info/")
  get "static_pages/ai4u" => redirect("http://ai-4-u.com/")
  get "static_pages/seamless" => redirect("http://shiropen.com/")
  get "static_pages/mit" => redirect("https://www.technologyreview.jp/")
  get "static_pages/deeplearning" => redirect("https://github.com/dennybritz/deeplearning-papernotes/blob/master/README.md")
  
  get "static_pages/iotnews" => redirect("https://iotnews.jp/")
  get "static_pages/iottoday" => redirect("http://iottoday.jp/")
  get "static_pages/monoist" => redirect("http://monoist.atmarkit.co.jp/")
  get "static_pages/techfactory" => redirect("http://techfactory.itmedia.co.jp/")
  
  get "static_pages/bcbiz" => redirect("http://gaiax-blockchain.com/")
  get "static_pages/btcn" => redirect("https://btcnews.jp/")
  get "static_pages/doublehash" => redirect("http://doublehash.me/")
  
  get "static_pages/netcommerce" => redirect("https://www.netcommerce.co.jp/blog")
  get "static_pages/itpro" => redirect("http://itpro.nikkeibp.co.jp/")
  get "static_pages/itmedia" => redirect("http://www.itmedia.co.jp/")
  get "static_pages/techcrunch" => redirect("http://jp.techcrunch.com/")
  get "static_pages/bridge" => redirect("http://thebridge.jp/")
  get "static_pages/cloud" => redirect("https://cloud.watch.impress.co.jp/")
  
  get "static_pages/moguravr" => redirect("http://www.moguravr.com/")
  get "static_pages/vrbeat" => redirect("http://www.vrbeat.net/")
  
  get "static_pages/drone" => redirect("https://www.drone.jp/")
  get "static_pages/dronemedia" => redirect("http://dronemedia.jp/")
  get "static_pages/bank" => redirect("https://dronebank.jp/")
  
  get "static_pages/makers" => redirect("http://makerslove.com/")
  get "static_pages/itmedia3d" => redirect("http://www.itmedia.co.jp/keywords/3d_printer.html")
  
  get "static_pages/marketing" => redirect("http://marketing.itmedia.co.jp/")
  get "static_pages/digiday" => redirect("http://digiday.jp/")
  get "static_pages/markezine" => redirect("https://markezine.jp/")
  
  get "static_pages/fintechonline" => redirect("https://fintechonline.jp/")
  get "static_pages/itmediafintech" => redirect("http://www.itmedia.co.jp/enterprise/subtop/fintech/index.html")
  get "static_pages/finte" => redirect("https://www.enigma.co.jp/media/")
 
  ##### パートナーリンク
  get "static_pages/kikagaku" => redirect("https://www.kikagaku.co.jp/")
  get "static_pages/justincase" => redirect("https://justincase.jp/")
  get "static_pages/glc" => redirect("https://geeklabs.co.jp/")
  get "static_pages/aisprits" => redirect("http://aispirits.com/") 
 
  ##### ノウハウ伝授リンク
  get "learning" => 'learning#index' 
  get "learning/shin-nihon" => redirect("http://www.meti.go.jp/committee/sankoushin/shin_sangyoukouzou/pdf/013_06_00.pdf")
  get "learning/business1" => 'learning#business1'
  get "learning/business2" => 'learning#business2'
  get "learning/business3" => 'learning#business3'
  
  get "learning/data1" => 'learning#data1'
  get "learning/data2" => 'learning#data2'
  
  get "static_pages/learning/business1" => redirect("http://www.edutech.co.jp/learning/business1")
  get "learning/seminar" => redirect("http://www.edutech.co.jp/static_pages/seminar")
  get "static_pages/dx-media" => redirect("https://www.dx-media.net/")


  ##### 問い合わせフォーム
  get 'inquiry' => 'inquiry#index' 
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  
  ##### 問い合わせ確認画面
  post 'inquiry/confirm' => 'inquiry#confirm'
  ##### 問い合わせ完了画面
  post 'inquiry/thanks' => 'inquiry#thanks'
  
  ##### 申し込みフォーム
  get 'reserve' => 'reserve#index' 
  get 'reserve/confirm' => redirect("/reserve")
  get 'reserve/thanks' => redirect("/reserve")
  ##### 申し込み確認画面
  post 'reserve/confirm' => 'reserve#confirm'
  ##### 申し込み完了画面
  post 'reserve/thanks' => 'reserve#thanks'
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :name,   length: { minimum: 2, :too_short => '名前を入力して下さい。'}, presence: true
  validates :email,  length: { minimum: 3, :too_short => 'メールアドレスを入力して下さい。'}, presence: true
  validates_numericality_of :phone, { :message => '電話番号は数字で入力して下さい。'}
  validates :message, length: { minimum: 2, :message => '問い合わせ内容を入力して下さい。'}, presence: true
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
 ##### 問い合わせフォーム画面を表示する
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  ##### 問い合わせフォームから入力された内容をチェックする
  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # 入力内容に問題ない場合、問い合わせ確認画面を表示
      render :action => 'confirm'
    else
      # 入力内容に問題ある場合、問い合わせ画面を再表示
      render :action => 'index'
    end
  end

  ##### 問い合わせ完了画面の処理
  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    
    if params[:back]
      render :action => 'index'
      
    else
      # 問い合わせ内容をメール送信
      @inquiry = Inquiry.new(inquiry_params)
      InquiryMailer.received_email(@inquiry).deliver
      InquiryMailer.welcome_email(@inquiry).deliver 
  
      # 問い合わせ完了画面を表示する
      render :action => 'thanks'
    end
  end

  ##### Strong Parametersで問い合わせ画面からの入力を許可するリクエストパラメータを指定する
  def inquiry_params
    params.require(:inquiry).permit(
      :name, :belonging, :email, :phone, :message
    )
  end

end

app/views/inquiry/confirm.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 col-xs-12">

    <div class="page-header">
      <h1>問い合わせ確認画面</h1>
    </div>

    <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
            <table class="table">
              <tr>
                <th>名前</th>
                <td>
                  <%= f.hidden_field :name %>
                  <%= @inquiry.name %>
                </td>
              </tr>
              
              <tr>
                <th>所属</th>
                <td>
                  <%= f.hidden_field :belonging %>
                  <%= @inquiry.belonging %>
                </td>
              </tr>
              
              <tr>
                <th>メールアドレス</th>
                <td>
                  <%= f.hidden_field :email %>
                  <%= @inquiry.email %>
                </td>
              </tr>
          
              <tr>
                <th>電話番号</th>
                <td>
                  <%= f.hidden_field :phone %>
                  <%= @inquiry.phone %>
                </td>
              </tr>
          
              <tr>
                <th>問い合わせ内容</th>
                <td>
                  <%= f.hidden_field :message %>
                  <%= simple_format(@inquiry.message) %>
                </td>
              </tr>
            </table>
            <h2><%= f.submit '送信', class: 'btn btn-primary' %>
            <%= f.submit '戻る', class: 'btn btn-primary', name: 'back' %></h2>
    <% end %>
  　</div>
</div>

app/views/inquiry/index.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
          <h1>問い合わせ画面</h1>
        </div>
        <% if @inquiry.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @inquiry.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="inquiry">
            <h1>名前<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :name, :size =>"27" %></h4><br>
            
            <h1>所属（お勤め先・学校など）<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :belonging, :size =>"27" %></h4><br>
            
            <h1>メールアドレス<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :email, :size =>"27" %></h4><br>
      
            <h1>電話番号<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :phone, :size =>"27" %></h4><br>
      
            <h1>問い合わせ内容<span class="text-danger"> (必須)</span></h1><br>
            <%= f.text_area :message  %><br>
 
            <h2><%= f.submit '確認', class: 'btn btn-primary' %></h2>
        <% end %>
        </div>
    </div>
</div>

app/views/inquiry/thanks.html.erb
<h1>問い合わせ完了画面</h1>

<h3>
　お問い合わせありがとうございました。<br>
　問い合わせ内容は管理者宛に送信しました。<br>
　後日担当者よりご連絡いたします。
</h3>