config/routes.rb
Rails.application.routes.draw do
  get 'learning/index'

  root to: 'static_pages#home'
  
  get "static_pages/seminar" => 'static_pages#seminar'
  get "static_pages/seminar2" => 'static_pages#seminar2'
  get "static_pages/middle" => 'static_pages#middle'
  get "static_pages/pmo" => 'static_pages#pmo'
  get "static_pages/about" => 'static_pages#about'
  get "static_pages/approach" => 'static_pages#approach'
  get "static_pages/member" => 'static_pages#member'  
  get "static_pages/voice" => 'static_pages#voice'  
  get "static_pages/privacy" => 'static_pages#privacy' 
  get "static_pages/development" => 'static_pages#development' 
  get "static_pages/media" => 'static_pages#media'
  get "static_pages/sitemap" => 'static_pages#sitemap' 
  get "static_pages/strength" => 'static_pages#strength'  
  get "static_pages/consulting" => 'static_pages#consulting' 
  get "static_pages/consulting2" => 'static_pages#consulting2'
  get "static_pages/bot" => 'static_pages#bot' 
  get "static_pages/service" => 'static_pages#service'
  
  
  ##### メディアリンク
  get "static_pages/ainow" => redirect("http://ainow.ai/")
  get "static_pages/robotstart" => redirect("https://robotstart.info/")
  get "static_pages/ai4u" => redirect("http://ai-4-u.com/")
  get "static_pages/seamless" => redirect("http://shiropen.com/")
  get "static_pages/mit" => redirect("https://www.technologyreview.jp/")
  get "static_pages/deeplearning" => redirect("https://github.com/dennybritz/deeplearning-papernotes/blob/master/README.md")
  
  get "static_pages/iotnews" => redirect("https://iotnews.jp/")
  get "static_pages/iottoday" => redirect("http://iottoday.jp/")
  get "static_pages/monoist" => redirect("http://monoist.atmarkit.co.jp/")
  get "static_pages/techfactory" => redirect("http://techfactory.itmedia.co.jp/")
  
  get "static_pages/bcbiz" => redirect("http://gaiax-blockchain.com/")
  get "static_pages/btcn" => redirect("https://btcnews.jp/")
  get "static_pages/doublehash" => redirect("http://doublehash.me/")
  
  get "static_pages/netcommerce" => redirect("https://www.netcommerce.co.jp/blog")
  get "static_pages/itpro" => redirect("http://itpro.nikkeibp.co.jp/")
  get "static_pages/itmedia" => redirect("http://www.itmedia.co.jp/")
  get "static_pages/techcrunch" => redirect("http://jp.techcrunch.com/")
  get "static_pages/bridge" => redirect("http://thebridge.jp/")
  get "static_pages/cloud" => redirect("https://cloud.watch.impress.co.jp/")
  
  get "static_pages/moguravr" => redirect("http://www.moguravr.com/")
  get "static_pages/vrbeat" => redirect("http://www.vrbeat.net/")
  
  get "static_pages/drone" => redirect("https://www.drone.jp/")
  get "static_pages/dronemedia" => redirect("http://dronemedia.jp/")
  get "static_pages/bank" => redirect("https://dronebank.jp/")
  
  get "static_pages/makers" => redirect("http://makerslove.com/")
  get "static_pages/itmedia3d" => redirect("http://www.itmedia.co.jp/keywords/3d_printer.html")
  
  get "static_pages/marketing" => redirect("http://marketing.itmedia.co.jp/")
  get "static_pages/digiday" => redirect("http://digiday.jp/")
  get "static_pages/markezine" => redirect("https://markezine.jp/")
  
  get "static_pages/fintechonline" => redirect("https://fintechonline.jp/")
  get "static_pages/itmediafintech" => redirect("http://www.itmedia.co.jp/enterprise/subtop/fintech/index.html")
  get "static_pages/finte" => redirect("https://www.enigma.co.jp/media/")
 
  ##### パートナーリンク
  get "static_pages/kikagaku" => redirect("https://www.kikagaku.co.jp/")
  get "static_pages/justincase" => redirect("https://justincase.jp/")
  get "static_pages/glc" => redirect("https://geeklabs.co.jp/")
  get "static_pages/aisprits" => redirect("http://aispirits.com/") 
 
  ##### ノウハウ伝授リンク
  get "learning" => 'learning#index' 
  get "learning/shin-nihon" => redirect("http://www.meti.go.jp/committee/sankoushin/shin_sangyoukouzou/pdf/013_06_00.pdf")
  get "learning/business1" => 'learning#business1'
  get "learning/business2" => 'learning#business2'
  get "learning/business3" => 'learning#business3'
  
  get "learning/data1" => 'learning#data1'
  get "learning/data2" => 'learning#data2'
  
  get "static_pages/learning/business1" => redirect("http://www.edutech.co.jp/learning/business1")
  get "learning/seminar" => redirect("http://www.edutech.co.jp/static_pages/seminar")
  get "static_pages/dx-media" => redirect("https://www.dx-media.net/")


  ##### 問い合わせフォーム
  get 'inquiry' => 'inquiry#index' 
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  
  ##### 問い合わせ確認画面
  post 'inquiry/confirm' => 'inquiry#confirm'
  ##### 問い合わせ完了画面
  post 'inquiry/thanks' => 'inquiry#thanks'
  
  ##### 申し込みフォーム
  get 'reserve' => 'reserve#index' 
  get 'reserve/confirm' => redirect("/reserve")
  get 'reserve/thanks' => redirect("/reserve")
  ##### 申し込み確認画面
  post 'reserve/confirm' => 'reserve#confirm'
  ##### 申し込み完了画面
  post 'reserve/thanks' => 'reserve#thanks'
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  validates :reserved_day,  presence: { :message => '日程をチェックして下さい。'}
  validates :sponsor,  presence: { :message => '領収書先をチェックして下さい。'}
  validates :name,   length: { minimum: 2, :too_short => '名前を入力して下さい。'}
  validates :email,  length: { minimum: 3, :too_short => 'メールアドレスを入力して下さい。'}
  validates_numericality_of :phone, { :message => '電話番号は数字で入力して下さい。'}
  validates_numericality_of :post, { :message => '郵便番号は数字で入力して下さい。'}
  validates :address1,  length: { minimum: 1, :too_short => '都道府県を入力して下さい。'}
  validates :address2,  length: { minimum: 1, :too_short => '市区町村を入力して下さい。'}
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
 ##### 問い合わせフォーム画面を表示する
  def index
    @reserve = Reserve.new
    render :action => 'index'
  end

  ##### 問い合わせフォームから入力された内容をチェックする
  def confirm
    @reserve = Reserve.new(reserve_params)
    if @reserve.valid?
      # 入力内容に問題ない場合、問い合わせ確認画面を表示
      render :action => 'confirm'
    else
      # 入力内容に問題ある場合、問い合わせ画面を再表示
      render :action => 'index'
    end
  end

  ##### 問い合わせ完了画面の処理
  def thanks
    @reserve = Reserve.new(reserve_params)
    
    if params[:back]
      render :action => 'index'
      
    else
      # 問い合わせ内容をメール送信
      @reserve = Reserve.new(reserve_params)
      ::ReserveMailer.received_email(@reserve).deliver
      ::ReserveMailer.welcome_email(@reserve).deliver 
  
      # 問い合わせ完了画面を表示する
      render :action => 'thanks'
    end
  end

  ##### Strong Parametersで問い合わせ画面からの入力を許可するリクエストパラメータを指定する
  def reserve_params
    params.require(:reserve).permit(
      :reserved_day, :name, :sponsor, :belonging, :email, :phone, :post, :address1, :address2, :message
    )
  end
end

app/views/reserve/confirm.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 col-xs-12">

    <div class="page-header">
      <h1>講座予約確認画面</h1>
    </div>

    <%= form_for @reserve, :url => reserve_thanks_path do |f| %>
            <table class="table">
              <tr>
                <th>申し込み日程</th>
                <td>
                  <%= f.hidden_field :reserved_day %>
                  <%= @reserve.reserved_day %>
                </td>
              </tr>

              <tr>
                <th>名前</th>
                <td>
                  <%= f.hidden_field :name %>
                  <%= @reserve.name %>
                </td>
              </tr>
              
              <tr>
                <th>領収書先</th>
                <td>
                  <%= f.hidden_field :sponsor %>
                  <%= @reserve.sponsor %>
                </td>
              </tr>
              
              <tr>
                <th>所属</th>
                <td>
                  <%= f.hidden_field :belonging %>
                  <%= @reserve.belonging %>
                </td>
              </tr>
              
              <tr>
                <th>メールアドレス</th>
                <td>
                  <%= f.hidden_field :email %>
                  <%= @reserve.email %>
                </td>
              </tr>
          
              <tr>
                <th>電話番号</th>
                <td>
                  <%= f.hidden_field :phone %>
                  <%= @reserve.phone %>
                </td>
              </tr>
              
              <tr>
                <th>郵便番号</th>
                <td>
                  <%= f.hidden_field :post %>
                  <%= @reserve.post %>
                </td>
              </tr>
          
              <tr>
                <th>都道府県</th>
                <td>
                  <%= f.hidden_field :address1 %>
                  <%= @reserve.address1 %>
                </td>
              </tr>

              <tr>
                <th>市区町村番地</th>
                <td>
                  <%= f.hidden_field :address2 %>
                  <%= @reserve.address2 %>
                </td>
              </tr>
              
              <tr>
                <th>追加コメント</th>
                <td>
                  <%= f.hidden_field :message %>
                  <%= simple_format(@reserve.message) %>
                </td>
              </tr>
            </table>
            <h2><%= f.submit '送信', class: 'btn btn-primary' %>
            <%= f.submit '戻る', class: 'btn btn-primary', name: 'back' %></h2>
    <% end %>
  　</div>
</div>

app/views/reserve/index.html.1.erb
<%= form_for @reserve, :url => reserve_confirm_path do |f| %>
  
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
          <h1>テクノロジー×ビジネス講座<br>
          申し込み画面</h1>
        </div>
            <div class="logo3">
                <h4>
                現在問合せフォームがシステムトラブルで利用できなくなっています。
                メールにてご予約日と名前を送っていただければ手続きのためのご返信をいたします。<br><br>
                ご予約はこちらのメールへ： <a href="mailto:admin@edutech.co.jp">admin@edutech.co.jp</a>
                </h4>
            </div>        
            <br><br><br><br><br><br><br>
        
        <% if @reserve.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @reserve.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="inquiry">            
        
            <h1>申し込み日程<span class="text-danger"> (必須)</span></h1><br>
            <h4>
            　<%= f.radio_button :reserved_day, '20190928' %>9/28(土)・9/29(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：四ツ谷3丁目アクトコール本社5F<br><br>
              <%= f.radio_button :reserved_day, '20191026' %>10/26(土)・10/27(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：四ツ谷3丁目アクトコール本社5F<br><br>
              <%= f.radio_button :reserved_day, '20191126' %>11/30(土)・11/1(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：四ツ谷3丁目アクトコール本社5F<br><br>
              <%= f.radio_button :reserved_day, '20191221' %>12/21(土)・12/22(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：四ツ谷3丁目アクトコール本社5F<br><br>
            </h4>

            <h1>名前<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :name, :size =>"27" %></h4><br>
          
            <h1>領収書先（個人/法人）<span class="text-danger"> (必須)</span></h1><br>
            <h4>※以下選択に合わせた電話番号・住所を記載ください。<br>  <br>         
             <%= f.radio_button :sponsor, '個人' %>個人
             <%= f.radio_button :sponsor, '法人' %>法人<br><br><br>
            </h4>
            
            <h1>所属（お勤め先・学校など）<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :belonging, :size =>"27" %></h4><br>
            
            <h1>メールアドレス<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :email, :size =>"27" %></h4><br>
      
            <h1>電話番号<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :phone, :size =>"27" %></h4><br>
            
            <h1>郵便番号（ハイフンなし数値のみ）<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :post, :size =>"13" %></h4><br>

            <h1>都道府県<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :address1, :size =>"13" %></h4><br>

            <h1>市区町村番地ビル名<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :address2, :size =>"27" %></h4><br>
            
            <h1>申込同意事項<span class="text-danger"> (必須)</span></h1><br>
            <h4>【キャンセルポリシー】<br>
                ・前日以降のご返金はできません。<br>
                ・1週間～2日前まで70％ご返金いたします。<br><br>
                【研修内容の取扱い】<br>
                ・研修で提供する文章については個人利用以外に再販などの事業目的の利用に向けた複製をお断りしています。<br><br>
                【ご請求処理について】<br>
                ・本研修はアクトコールグループの株式会社GLC様の会場をお借りし、代理店販売を依頼しております。研修費用等の請求などはGLC様を通して事前に実施させていただきます。<br><br>
                
             <%= f.radio_button :policy, 'ポリシーに同意' %>以上内容への同意表明<br><br>

            </h4>   

            <h1>ご要望等あればコメントしてください</h1><br>
            <%= f.text_area :message %><br>

         

            <h2><%= f.submit '確認', class: 'btn btn-primary' %></h2>
        <% end %>
        </div>
    </div>
</div>

app/views/reserve/index.html.erb
<%= form_for @reserve, :url => reserve_confirm_path do |f| %>
  
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
          <h1>テクノロジー×ビジネス講座<br>
          申し込み画面</h1>
        </div>
        
        <% if @reserve.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @reserve.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="inquiry">            
        
            <h1>申し込み日程<span class="text-danger"> (必須)</span></h1><br>
            <h4>
              <%= f.radio_button :reserved_day, '20191130' %>11/30(土)・12/1(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：A.R.I. Group Innovation Lab　東京都渋谷区渋谷1-13-7　ヒューリック渋谷ビル7F<br><br>
              <%= f.radio_button :reserved_day, '20190125' %>1/25(土)・1/26(日)：AIビジネス推進人材育成プログラム：12万円（税込）<br>時間:10:00～19:00 <br>会場：A.R.I. Group Innovation Lab　東京都渋谷区渋谷1-13-7　ヒューリック渋谷ビル7F<br><br>
            </h4>

            <h1>名前<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :name, :size =>"27" %></h4><br>
          
            <h1>領収書先（個人/法人）<span class="text-danger"> (必須)</span></h1><br>
            <h4>※以下選択に合わせた電話番号・住所を記載ください。<br>  <br>         
             <%= f.radio_button :sponsor, '個人' %>個人
             <%= f.radio_button :sponsor, '法人' %>法人<br><br><br>
            </h4>
            
            <h1>所属（お勤め先・学校など）<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :belonging, :size =>"27" %></h4><br>
            
            <h1>メールアドレス<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :email, :size =>"27" %></h4><br>
      
            <h1>電話番号<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :phone, :size =>"27" %></h4><br>
            
            <h1>郵便番号（ハイフンなし数値のみ）<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :post, :size =>"13" %></h4><br>

            <h1>都道府県<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :address1, :size =>"13" %></h4><br>

            <h1>市区町村番地ビル名<span class="text-danger"> (必須)</span></h1><br>
            <h4><%= f.text_field :address2, :size =>"27" %></h4><br>
            
            <h1>申込同意事項<span class="text-danger"> (必須)</span></h1><br>
            <h4>【キャンセルポリシー】<br>
                ・前日以降のご返金はできません。<br>
                ・1週間～2日前まで70％ご返金いたします。<br><br>
                【研修内容の取扱い】<br>
                ・研修で提供する文章については個人利用以外に再販などの事業目的の利用に向けた複製をお断りしています。<br><br>
                【ご請求処理について】<br>
                ・予約完了後、弊社担当者からご連絡させていただきます。<br><br>
                
             <%= f.radio_button :policy, 'ポリシーに同意' %>以上内容への同意表明<br><br>

            </h4>   

            <h1>ご要望等あればコメントしてください</h1><br>
            <%= f.text_area :message %><br>

         

            <h2><%= f.submit '確認', class: 'btn btn-primary' %></h2>
        <% end %>
        </div>
    </div>
</div>

app/views/reserve/thanks.html.erb
<h1>申し込み完了画面</h1>

<h3>テクノロジー講座への申し込みありがとうございました。<br>
　申し込み内容は管理者宛に送信しました。<br>
　後日担当者よりご連絡いたします。
</h3>