config/routes.rb
Rails.application.routes.draw do
  get 'learning/index'

  root to: 'static_pages#home'
  
  get "static_pages/seminar" => 'static_pages#seminar'
  get "static_pages/seminar2" => 'static_pages#seminar2'
  get "static_pages/middle" => 'static_pages#middle'
  get "static_pages/pmo" => 'static_pages#pmo'
  get "static_pages/about" => 'static_pages#about'
  get "static_pages/approach" => 'static_pages#approach'
  get "static_pages/member" => 'static_pages#member'  
  get "static_pages/voice" => 'static_pages#voice'  
  get "static_pages/privacy" => 'static_pages#privacy' 
  get "static_pages/development" => 'static_pages#development' 
  get "static_pages/media" => 'static_pages#media'
  get "static_pages/sitemap" => 'static_pages#sitemap' 
  get "static_pages/strength" => 'static_pages#strength'  
  get "static_pages/consulting" => 'static_pages#consulting' 
  get "static_pages/consulting2" => 'static_pages#consulting2'
  get "static_pages/bot" => 'static_pages#bot' 
  get "static_pages/service" => 'static_pages#service'
  
  
  ##### メディアリンク
  get "static_pages/ainow" => redirect("http://ainow.ai/")
  get "static_pages/robotstart" => redirect("https://robotstart.info/")
  get "static_pages/ai4u" => redirect("http://ai-4-u.com/")
  get "static_pages/seamless" => redirect("http://shiropen.com/")
  get "static_pages/mit" => redirect("https://www.technologyreview.jp/")
  get "static_pages/deeplearning" => redirect("https://github.com/dennybritz/deeplearning-papernotes/blob/master/README.md")
  
  get "static_pages/iotnews" => redirect("https://iotnews.jp/")
  get "static_pages/iottoday" => redirect("http://iottoday.jp/")
  get "static_pages/monoist" => redirect("http://monoist.atmarkit.co.jp/")
  get "static_pages/techfactory" => redirect("http://techfactory.itmedia.co.jp/")
  
  get "static_pages/bcbiz" => redirect("http://gaiax-blockchain.com/")
  get "static_pages/btcn" => redirect("https://btcnews.jp/")
  get "static_pages/doublehash" => redirect("http://doublehash.me/")
  
  get "static_pages/netcommerce" => redirect("https://www.netcommerce.co.jp/blog")
  get "static_pages/itpro" => redirect("http://itpro.nikkeibp.co.jp/")
  get "static_pages/itmedia" => redirect("http://www.itmedia.co.jp/")
  get "static_pages/techcrunch" => redirect("http://jp.techcrunch.com/")
  get "static_pages/bridge" => redirect("http://thebridge.jp/")
  get "static_pages/cloud" => redirect("https://cloud.watch.impress.co.jp/")
  
  get "static_pages/moguravr" => redirect("http://www.moguravr.com/")
  get "static_pages/vrbeat" => redirect("http://www.vrbeat.net/")
  
  get "static_pages/drone" => redirect("https://www.drone.jp/")
  get "static_pages/dronemedia" => redirect("http://dronemedia.jp/")
  get "static_pages/bank" => redirect("https://dronebank.jp/")
  
  get "static_pages/makers" => redirect("http://makerslove.com/")
  get "static_pages/itmedia3d" => redirect("http://www.itmedia.co.jp/keywords/3d_printer.html")
  
  get "static_pages/marketing" => redirect("http://marketing.itmedia.co.jp/")
  get "static_pages/digiday" => redirect("http://digiday.jp/")
  get "static_pages/markezine" => redirect("https://markezine.jp/")
  
  get "static_pages/fintechonline" => redirect("https://fintechonline.jp/")
  get "static_pages/itmediafintech" => redirect("http://www.itmedia.co.jp/enterprise/subtop/fintech/index.html")
  get "static_pages/finte" => redirect("https://www.enigma.co.jp/media/")
 
  ##### パートナーリンク
  get "static_pages/kikagaku" => redirect("https://www.kikagaku.co.jp/")
  get "static_pages/justincase" => redirect("https://justincase.jp/")
  get "static_pages/glc" => redirect("https://geeklabs.co.jp/")
  get "static_pages/aisprits" => redirect("http://aispirits.com/") 
 
  ##### ノウハウ伝授リンク
  get "learning" => 'learning#index' 
  get "learning/shin-nihon" => redirect("http://www.meti.go.jp/committee/sankoushin/shin_sangyoukouzou/pdf/013_06_00.pdf")
  get "learning/business1" => 'learning#business1'
  get "learning/business2" => 'learning#business2'
  get "learning/business3" => 'learning#business3'
  
  get "learning/data1" => 'learning#data1'
  get "learning/data2" => 'learning#data2'
  
  get "static_pages/learning/business1" => redirect("http://www.edutech.co.jp/learning/business1")
  get "learning/seminar" => redirect("http://www.edutech.co.jp/static_pages/seminar")
  get "static_pages/dx-media" => redirect("https://www.dx-media.net/")


  ##### 問い合わせフォーム
  get 'inquiry' => 'inquiry#index' 
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  
  ##### 問い合わせ確認画面
  post 'inquiry/confirm' => 'inquiry#confirm'
  ##### 問い合わせ完了画面
  post 'inquiry/thanks' => 'inquiry#thanks'
  
  ##### 申し込みフォーム
  get 'reserve' => 'reserve#index' 
  get 'reserve/confirm' => redirect("/reserve")
  get 'reserve/thanks' => redirect("/reserve")
  ##### 申し込み確認画面
  post 'reserve/confirm' => 'reserve#confirm'
  ##### 申し込み完了画面
  post 'reserve/thanks' => 'reserve#thanks'
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-inverse">
        <div class="footer">
              <h1 class="logo2">
              <%= image_tag "logo3.png" %>
              </h1>
              〒160-0023 東京都新宿区西新宿8-3-1<br>
              西新宿GFビル2F<br>
              問い合わせ先： <a href="mailto:admin@edutech.co.jp">admin@edutech.co.jp</a><br>
              <%= link_to "セミナーの予約", reserve_path %><br> 
              <%= link_to "サイトマップ", static_pages_sitemap_path %><br> 
              <%= link_to "プライバシーポリシー", static_pages_privacy_path %><br><br>  
              Copyright © EduTech Partners All rights reserved.<br>
        </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    
    <div class="container-fluid">
      <div class="navbar-inner">
        <div class="navbar-header">
          <button class="navbar-toggle" data-toggle="collapse" data-target="#mainNav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1 class="logo">
            <%= image_tag "logo4.png"  %>
          </h1>
        </div>
      </div>
      
      <div class = "collapse navbar-collapse" id="mainNav">
        <h1>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "トップ",  root_path %></li>
              <li><%= link_to "AI研修", static_pages_seminar_path %></li>
              <li><%= link_to "会社概要", static_pages_about_path %></li>
              <li><%= link_to "弊社の強み", static_pages_strength_path %></li>
              <li><%= link_to "弊社サービス", static_pages_service_path %></li>
              <li><%= link_to "メンバー", static_pages_member_path %></li>
              <li><%= link_to "最新テック動向", static_pages_media_path %></li>
          </ul>
        </h1>
      </div>
    
    </div>
  </nav>
</header>

app/views/layouts/_meta_tags.html.haml
%meta{charset: 'UTF-8'}/
%meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}

%link{media: 'handheld', rel: 'alternate', href: request.original_url}/

- # 各種メタタグのデフォルト設定
- # 必要に応じて各 View 内で上書きすること
- #
- # 例: set_meta_tags title: "ほげほげ"
= display_meta_tags default_meta_tags

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIプランナー育成支援：AI活用ならエデュテックパートナーズ</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= analytics_init if Rails.env.production? %>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
    <meta name="keywords" content="AI活用,AI企画,AIビジネス,AIセミナー,IoTセミナー,AI事例">
　　<meta name="description" content="AIビジネスプランナーを育成！AIのビジネス活用にお困りのあなたに、エデュテックパートナーズはAIビジネス企画立案ノウハウを提供します。">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>